// Generated by supersprite 9/30/2021, 7:49:35 PM - script/atlas.js
// These Sprite and SpriteImage types identical to those exported by supersprite
const spr : {
  bricks : Sprite;
  grass : Sprite;
  stone : Sprite;
  guy : Sprite;
} = {
  bricks: { width: 32, height: 32, originX: 0, originY: 0, images: [{ x: 0, y: 0, t: [0.0625,0,0,0,0.0625,0,0,0,1] }, ]},
  grass: { width: 32, height: 32, originX: 0, originY: 0, images: [{ x: 32, y: 0, t: [0.0625,0,0,0,0.0625,0,0.0625,0,1] }, ]},
  stone: { width: 32, height: 32, originX: 0, originY: 0, images: [{ x: 64, y: 0, t: [0.0625,0,0,0,0.0625,0,0.125,0,1] }, ]},
  guy: { width: 16, height: 16, originX: 0, originY: 0, images: [{ x: 96, y: 0, t: [0.03125,0,0,0,0.03125,0,0.1875,0,1] }, { x: 128, y: 0, t: [0.03125,0,0,0,0.03125,0,0.25,0,1] }, { x: 160, y: 0, t: [0.03125,0,0,0,0.03125,0,0.3125,0,1] }, { x: 192, y: 0, t: [0.03125,0,0,0,0.03125,0,0.375,0,1] }, { x: 224, y: 0, t: [0.03125,0,0,0,0.03125,0,0.4375,0,1] }, { x: 256, y: 0, t: [0.03125,0,0,0,0.03125,0,0.5,0,1] }, ]},
};
interface Sprite {
    width: number;
    height: number;
    originX: number;
    originY: number;
    images: SpriteImage[];
}

interface SpriteImage {
    x: number;
    y: number;
    /** A precomputed 3x3 matrix, used to slice this sprite image out of the texture atlas. */
    t: [number, number, number, number, number, number, number, number, number];
}
export default spr;